version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
    environment:
      - node.name=es-node
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - ELASTIC_PASSWORD=MiPassMuySeguro!2025
      - KIBANA_PASSWORD=MiPassMuySeguro!2025
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -u elastic:MiPassMuySeguro!2025 -f http://localhost:9200 || exit 1"
        ]
      interval: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=MiPassMuySeguro!2025
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
